// Proposed project directions, not claims that each has been completed or peer reviewed.
// Each row supplies a different subject or mechanism to investigate.
const expandedFields=[
['biology','Biology & bioinformatics','data','geo','gene activity under stress|gene activity across tissues|missing values in gene tables|outliers in expression measurements|sample-label mistakes|different ways to normalize gene counts|small versus large sample groups|gene-ranking stability|batch effects between experiments|clustering similar gene profiles|repeatability across public studies|visual explanations of gene activity'],
['ecology','Ecology & conservation','sim','joss','predator and prey population cycles|habitat fragmentation|species competition for food|invasive species spread|seasonal migration routes|pollinator network failures|forest-fire spread on a grid|overfishing and recovery|wildlife corridors|resource sharing in a food web|seed dispersal patterns|ecosystem recovery after a shock'],
['chemistry','Chemistry & molecules','sim','joss','reaction speed and temperature|diffusion through a membrane|mixing particles in a container|reversible reaction equilibrium|random molecular collisions|concentration and reaction time|adsorption on a surface|gas pressure in a virtual box|crystal growth on a grid|molecular random walks|reaction-network bottlenecks|competing reaction pathways'],
['physics','Physics & mechanics','sim','indie','pendulum motion at large angles|coupled pendulums|wave interference|standing waves on a string|projectile motion with drag|spring resonance|heat flow along a rod|light refraction at a boundary|sound beats|orbital energy drift|collisions with different elasticity|electric fields around charges'],
['climate','Climate & weather','data','nasa','temperature trends across regions|heat-wave definitions|rainfall variability across seasons|missing weather observations|urban and nearby rural temperatures|sea-surface temperature changes|seasonal snow coverage|drought-index sensitivity|extreme-rainfall thresholds|different averaging windows|outliers in weather records|short-term variation versus long-term trends'],
['geography','Geography & maps','sim','indie','district boundary choices|map distortion at different latitudes|nearest-facility access|flood spread on a height grid|walking distance versus straight-line distance|population clustering|Voronoi service areas|route detours around barriers|map color scales|geographic sampling bias|grid size in density maps|placement of shared facilities'],
['transport','Transport & cities','sim','indie','traffic-light timing|bus bunching|school commute routing|train-platform queues|bike-lane network gaps|ambulance dispatch in a synthetic city|carpool matching|bus-stop placement|pedestrian crossing delays|road closures and rerouting|parking search traffic|crowding across transit routes'],
['energy','Energy & resources','sim','joss','solar output and cloud variation|battery charging schedules|household peak electricity demand|power sharing between buildings|wind-output variability|energy storage losses|electricity pricing windows|electric-vehicle charging queues|microgrid recovery after failure|renewable supply and demand mismatch|heat loss from buildings|water-pump scheduling'],
['music','Music & sound','signal','indie','rhythm and syncopation|notes inside a chord|tempo changes|musical tuning systems|waveform shapes and timbre|reverb and room size|audio compression artifacts|melody repetition|beat detection under noise|silence and perceived phrasing|pitch estimation errors|drum-pattern variation'],
['film','Film & visual storytelling','creative','pudding','scene order and suspense|camera framing and sympathy|editing pace and tension|color choices and mood|sound effects and interpretation|silent versus narrated scenes|subtitles and comprehension|unreliable narrators|parallel timelines|repeated visual motifs|offscreen events|different endings to one story'],
['writing','Writing & literature','text','gutenberg','who speaks in a novel|how narrators describe strangers|class markers in dialogue|place descriptions across chapters|metaphors for technology|letters versus spoken dialogue|changes in sentence length|unreliable narration clues|gendered descriptions of work|repeated images of nature|translation of ambiguous phrases|how chapter openings shape expectations'],
['philosophy','Philosophy & ethics','argument','gutenberg','fairness in allocating a scarce resource|consent in a digital setting|privacy versus collective benefit|responsibility for an automated decision|what counts as an explanation|freedom of expression and moderation|identity across a changing digital self|obligations to future generations|ownership of a remix|what makes a promise binding|whether intention changes blame|knowledge from conflicting testimony'],
['law','Law & legal language','argument','joss','ambiguity in a fictional contract|exceptions to a fictional rule|conflicting definitions|plain-language rewrites|evidence versus allegation|rules with overlapping jurisdictions|time limits in a fictional process|appeal routes in a fictional policy|rights and obligations in a sample agreement|precedent in a made-up dispute|missing facts that change an outcome|formal rules versus everyday expectations'],
['policy','Public policy & governance','sim','worldbank','scholarship eligibility thresholds|public-library placement|school funding rules|public-service waiting lists|food-distribution schedules|local budget allocation|housing allocation in a synthetic city|transit subsidy design|water rationing rules|public consultation sampling|benefit cliffs|emergency resource allocation'],
['psychology','Psychology & cognition','sim','joss','spaced repetition schedules|memory decay assumptions|response-time outliers|attention switching costs|confirmation bias in evidence selection|anchoring in a synthetic decision model|reward schedules and persistence|group conformity rules|different ways to summarize a survey|small-sample effects|practice effects in repeated tasks|order effects in a simulated questionnaire'],
['education','Education & learning','software','joss','fraction explanations|proof-step feedback|reading comprehension prompts|spaced-practice planning|common algebra mistakes|vocabulary recall|source-evaluation exercises|misleading-chart lessons|code-tracing exercises|timeline understanding|unit conversion practice|comparing alternative explanations'],
['games','Games & interactive worlds','sim','indie','resource scarcity in a strategy game|cooperation in repeated games|pathfinding around moving obstacles|procedural dungeon layouts|difficulty curves|turn-order advantage|in-game auction rules|fog of war|NPC resource sharing|level generation with constraints|economies with inflation|balancing asymmetric characters'],
['security','Cybersecurity','software','systems','SQL-injection prevention in a toy app|path-traversal protection|permission checks|dependency-risk reporting|password-strength explanations|input-validation failures|secure file-upload rules|rate-limiting strategies|log tampering detection|session expiry|cross-site scripting prevention|secret detection in synthetic repositories'],
['privacy','Privacy & digital rights','software','joss','location-data rounding|metadata removal from images|data retention schedules|consent settings|sensitive text redaction|anonymous survey summaries|link tracking detection|privacy notices in plain language|permission-request explanations|deletion verification|synthetic-data generation|reidentification in fictional records'],
['algorithms','Algorithms & mathematics','sim','systems','sorting with nearly ordered data|shortest paths on sparse graphs|matching students to projects|bin packing|cache replacement|job scheduling|search on different tree shapes|approximate nearest neighbors|set cover|network flow bottlenecks|hash collisions|randomized versus greedy choices'],
['web','Web development & tools','software','joss','offline reading|keyboard navigation|browser-tab organization|large-table rendering|broken-link checking|form-error explanations|undo and redo|page-load bottlenecks|document-version comparison|search over local notes|reliable autosave|data export and reimport'],
['accessibility','Accessibility & inclusive design','software','design','keyboard-only forms|screen-reader chart descriptions|captions with speaker labels|colorblind-friendly maps|reduced-motion interfaces|large-text layouts|plain-language instructions|error recovery without a mouse|accessible data tables|focus order in dialogs|image descriptions|low-bandwidth reading'],
['sports','Sports & performance','data','pudding','cricket batting strike-rate comparisons|cricket bowling economy across match phases|football shot-location summaries|basketball shot selection|tennis serve success by score|badminton rally length|running pace variability|chess opening outcomes|team rankings under different scoring rules|home versus away performance|small-sample player comparisons|missing matches in a sports dataset'],
['finance','Money & financial systems','sim','worldbank','compound interest and fees|inflation and purchasing power|loan repayment schedules|emergency fund scenarios|subscription cost over time|transaction-fee structures|household budget shocks|savings goals with irregular income|diversification in a synthetic market|exchange-rate scenarios|credit-scoring assumptions on fictional data|price changes and shopping baskets']
];
const extraSources={
geo:{title:'NCBI Gene Expression Omnibus',url:'https://www.ncbi.nlm.nih.gov/geo/info/overview.html',type:'Public data repository',lesson:'A possible starting place for gene-expression data. Choose a specific study and check its metadata and reuse conditions; none is preselected here.'},
nasa:{title:'NASA Open Data Portal',url:'https://data.nasa.gov/dataset',type:'Public data catalog',lesson:'A place to find environmental and space data. Availability, units, coverage, and reuse conditions must be checked for the chosen dataset.'},
worldbank:{title:'World Bank Indicators API documentation',url:'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api',type:'Public data documentation',lesson:'A reference for economic and social indicators. Simulation briefs use fictional data; these indicators do not validate their assumptions.'},
gutenberg:{title:'Project Gutenberg',url:'https://www.gutenberg.org/',type:'Digital text collection',lesson:'A place to find older texts. Public-domain status is jurisdiction-specific; translations and editions may have separate rights.'}
};
const topicLabel=s=>s.charAt(0).toUpperCase()+s.slice(1);
function makeCatalogProject(field,topic,index){const [id,label,mode,source]=field;let p={title:topicLabel(topic),source,catalogKind:'proposed',id:`${id}-${index}`};
if(mode==='sim')Object.assign(p,{question:`What changes in ${topic} when you alter one rule or setting?`,artifact:`A browser simulator of ${topic}, with controls and a chart comparing two settings.`,method:`Write down a simple model of ${topic}. State its assumptions. Keep all but one setting fixed, run both versions, and record the outcomes. Use fictional or simulated inputs.`,evaluate:'Check a tiny case whose answer you can calculate yourself. Repeat larger runs and measure the change in outcomes and runtime. Explain what your simplified model leaves out.',start:`Draw a 10-example model of ${topic}. Calculate one outcome by hand, then reproduce it in code.`,stretch:'Add a second interacting factor. Find a case where your first conclusion no longer holds.'});
if(mode==='data')Object.assign(p,{question:`Does the pattern in ${topic} survive a different way of selecting or cleaning the data?`,artifact:`A small data explorer for ${topic}, with the raw sample, charts, and a repeatable analysis.`,method:`Find one reusable dataset containing the measurements needed for ${topic}. Inspect units, missing values, and collection methods. Compare two clearly stated analysis choices on the same sample. If no suitable dataset is available, start with labeled synthetic data.`,evaluate:'Check calculations against a small hand-worked sample. Show sample size and missing values. Compare findings on a held-out sample; a relationship does not prove cause.',start:`Write the exact columns you need for ${topic}. Find or create 20 example rows, then make one chart.`,stretch:'Repeat on a second suitable dataset and explain disagreements instead of hiding them.'});
if(mode==='software')Object.assign(p,{question:`Can you build a useful tool for ${topic} that still works on difficult examples?`,artifact:`A focused web tool for ${topic}, plus sample inputs, expected outputs, and clear instructions.`,method:`Define one user task involving ${topic}. Write five ordinary and five difficult examples before building. Implement the simplest working approach and compare it with an existing approach. Security projects run only in your own toy app; privacy projects use fictional records.`,evaluate:'Run the expected-output examples and record failures. Check keyboard use, error messages, and whether a second person can complete the task from your instructions.',start:`Write three input/output examples for ${topic}. Build just one working example.`,stretch:'Add difficult inputs and explain the tradeoff between speed, correctness, and ease of use.'});
if(mode==='text')Object.assign(p,{question:`What can close reading reveal about ${topic}, and what does simple counting miss?`,artifact:`An annotated reading page about ${topic}, linking every chart and interpretation to passages.`,method:`Choose one legally reusable text or a small related collection. Define what counts as an example of ${topic}. Annotate passages, compare patterns, and deliberately look for exceptions.`,evaluate:'Have a second reader review a small sample. Record disagreement. Support interpretations with passages and explain why a count may oversimplify them.',start:`Choose 10 passages relevant to ${topic}. Write a short note explaining three examples and one exception.`,stretch:'Compare another author, period, or translation while keeping source-selection decisions visible.'});
if(mode==='creative')Object.assign(p,{question:`How does changing ${topic} alter the way a short story is understood?`,artifact:`Two digital versions of one original short scene, plus a commentary on the creative choices.`,method:`Create your own scene with fixed characters and events. Change only ${topic} between the two versions. Use original or legally reusable images and sound. Ask a few readers what they understood.`,evaluate:'Compare specific reader interpretations, not just likes. Explain which choices achieved your intention and include reactions that challenge it.',start:`Write a one-minute scene and storyboard two versions focused on ${topic}.`,stretch:'Create a third version that challenges the interpretation you expected.'});
if(mode==='argument')Object.assign(p,{question:`Which missing detail changes the answer to a question about ${topic}?`,artifact:`An interactive casebook about ${topic}, with competing arguments and fictional examples.`,method:`Write a narrowly framed question about ${topic}. Present two defensible positions. Create fictional cases that differ in one important fact. Cite real texts where you rely on them; legal examples are educational and do not assess real disputes.`,evaluate:'Check that each position is represented fairly. Ask a reader to identify the assumptions and test whether your reasoning remains consistent across the cases.',start:`Write two fictional cases about ${topic} that differ in one fact. Explain why that fact might change your answer.`,stretch:'Find a counterexample that makes you revise a rule, then show the revision openly.'});
if(mode==='signal')Object.assign(p,{question:`Can you make ${topic} visible and audible, and explain how changing one setting changes it?`,artifact:`A browser sound experiment for ${topic}, with generated audio, a waveform, and controls.`,method:`Generate short sounds yourself using simple waveforms. Change one parameter related to ${topic}, keeping others fixed. Show the waveforms alongside a plain-language explanation. Start muted and let the listener control playback.`,evaluate:'Check frequencies and timing against values you set. Compare predicted changes with the generated signals and collect optional listener descriptions without making clinical claims.',start:`Generate two one-second sounds that differ only in ${topic}. Plot both and explain the difference.`,stretch:'Add noise or a second signal and show where the simple explanation stops being enough.'});
return p;}
const simulationExperiments={
ecology:'predator birth rate=>the time prey populations need to recover;the number of barriers between habitats=>the number of animals that can reach food;available food=>which of two species survives;the number of starting invaders=>how quickly they spread across a grid;the distance between resting sites=>how many simulated migrants finish a journey;the loss of the most-connected pollinator=>how many plants lose every pollinator;the gap between trees=>how far a simulated fire travels;the proportion of fish caught each season=>the time a fish population needs to recover;the width of a wildlife corridor=>how many animals cross between habitats;the removal of one food-web species=>which other populations decline;seed travel distance=>the number of new patches reached;the strength of one population shock=>whether a simplified ecosystem returns to its starting state',
chemistry:'the temperature parameter in a stated reaction model=>the time reactants take to halve;the size of membrane openings=>the time particles need to spread evenly;the stirring rule=>how quickly two particle colors mix;forward versus reverse reaction rates=>the final ratio of reactants to products;particle density=>the number of collisions per simulated second;starting concentration=>the time a simple reaction takes to finish;the number of surface binding sites=>the number of particles attached at equilibrium;particle speed=>the collision count at the walls of a virtual box;the chance a particle sticks to a crystal=>the shape of the growing crystal;random-walk step size=>the average distance traveled;the slowest step in a reaction network=>total completion time;the rates of two competing reaction paths=>which final product is more common',
physics:'starting angle=>how accurate the small-angle pendulum formula remains;spring coupling strength=>how fast energy moves between two pendulums;the distance between two wave sources=>where bright and dark interference bands appear;string length=>the frequencies of standing waves;air-drag strength=>a projectile’s landing distance;driving frequency=>the maximum movement of a spring;rod conductivity=>how quickly a temperature difference fades;the refractive-index ratio=>the angle a light ray bends;the gap between two sound frequencies=>the number of beats per second;simulation time step=>how much orbital energy drifts;the elasticity of a collision=>how much kinetic energy is retained;the spacing between two charges=>the locations where their electric fields cancel',
geography:'where you draw district boundaries=>how many districts each synthetic group wins;the map projection=>the apparent relative size of two regions;facility location=>the longest journey a resident must make;water level=>which cells of a synthetic height map flood;road barriers=>the difference between walking and straight-line distance;the clustering of residents=>where a service center works best;the number of service sites=>the size of each site’s nearest-service area;one blocked street=>the extra distance of the best remaining route;map color thresholds=>which districts appear high-risk;sampling only near roads=>the estimated distribution of synthetic residents;density-grid size=>which apparent hotspots remain visible;the number of shared facilities=>how evenly travel distance is distributed',
transport:'traffic-light cycle length=>average waiting time at a simulated junction;uneven passenger boarding time=>the gap between consecutive buses;the order of school pickup stops=>the longest student journey;train arrival spacing=>the maximum platform queue;one missing bike-lane connection=>the extra distance of a bike-only route;the placement of two ambulance stations=>response times in a fictional city;maximum carpool detour=>the number of matched riders;the distance between bus stops=>total walking plus bus journey time;pedestrian green-light duration=>the number left waiting after a crossing cycle;the loss of one road=>the number of disconnected origin-destination pairs;available parking spaces=>the number of extra vehicle trips;frequency on the busiest route=>crowding across two connecting bus routes',
energy:'the length of a cloud-cover event=>energy delivered by a fictional solar array;charging time windows=>peak demand on a shared battery charger;the timing of household appliances=>the highest hourly electricity demand;the sharing rule between buildings=>the amount of unused generated energy;wind-speed variability in a stated model=>how often output falls below demand;charge-discharge efficiency=>the energy recovered from storage;the peak-price window=>the cost of a fixed daily usage schedule;the number of charging ports=>waiting time for simulated vehicles;the failure of one generator=>unserved demand in a toy microgrid;the share of solar generation=>the storage needed to cover evening demand;wall heat-loss rate=>the heat needed to hold a virtual room at a fixed temperature;the timing of pump operation=>the cost of filling a fixed-volume water tank',
policy:'a scholarship cutoff=>the number of almost-identical applicants treated differently;the placement of two libraries=>the share of fictional residents within walking distance;per-student versus needs-based funding=>resources received by each fictional school;the rule for ordering a waiting list=>waiting times for different applicants;delivery frequency=>stockouts in a simulated food network;equal versus population-weighted budgets=>spending per fictional resident;a housing selection rule=>the mix of households selected;flat versus targeted transit subsidies=>the distribution of benefits in fictional households;equal versus needs-based water limits=>the number of households below a stated minimum;who responds to a consultation=>the apparent support for a policy in a synthetic population;an income eligibility cutoff=>take-home resources just above and below the cutoff;the rule for allocating emergency supplies=>the number of fictional sites whose basic needs are met',
psychology:'the gap between practice sessions in a memory model=>the predicted number of items remembered;the assumed memory-decay rate=>the recommended review schedule;the rule for excluding unusually slow responses=>the estimated typical response time;the assumed cost of switching tasks=>total completion time for the same task list;a preference for confirming evidence=>how often a simulated agent rejects a false belief;the weight assigned to an initial number=>the final estimate in a fictional decision model;the frequency of rewards=>persistence in a stated toy behavior model;the proportion of neighbors who agree=>the time a simulated opinion spreads;mean versus median summaries=>the story told by a synthetic survey;sample size=>how often a random sample misses the true population average;the size of a simulated practice effect=>the apparent improvement between two tests;question order=>responses under an explicitly stated order-effect model',
games:'resource regeneration speed=>cooperation between simulated players;the probability of another round=>cooperation in a repeated game;obstacle movement speed=>pathfinding success and travel distance;room-connection rules=>the number of reachable dungeon rooms;the increase in enemy strength per level=>completion rate for a fixed simulated player;who moves first=>win rates under two fixed strategies;auction bidding rules=>price and allocation of a scarce in-game item;the visible radius=>how often an agent reaches a goal;the NPC sharing rule=>the number of agents left without resources;minimum room size=>the variety of valid generated levels;the amount of new currency per round=>item prices in a toy game economy;one character’s ability cooldown=>win rates under a fixed combat model',
algorithms:'the fraction of already sorted items=>the work done by two sorting methods;graph edge density=>runtime of two shortest-path methods;student preference conflicts=>the number receiving a preferred project;the order items arrive=>the number of bins used by two packing rules;the pattern of repeated requests=>cache misses under two replacement rules;job ordering=>average waiting time and missed deadlines;tree shape=>the number of comparisons needed for search;the search approximation setting=>speed versus missed nearest neighbors;the overlap between sets=>how far a greedy cover is from the best small-case cover;capacity on one network edge=>maximum possible flow;the distribution of keys=>hash-table collisions;random versus greedy choices=>solution quality over repeated runs',
finance:'an annual fee=>the final balance of a fictional savings account;the inflation assumption=>the future cost of a fixed shopping basket;extra repayments=>total interest in a fictional loan schedule;the length of an income interruption=>how long a stated emergency fund lasts;the number of subscriptions=>total spending over one year;flat versus percentage fees=>the cost of small and large transactions;an unexpected monthly expense=>the time a fictional budget needs to recover;income variability=>the chance of reaching a fixed savings goal;the correlation between two fictional assets=>variation in portfolio outcomes;the exchange-rate assumption=>the cost of a fixed foreign-currency purchase;the weight of one credit-score input=>decisions for nearly identical fictional applicants;price increases in different product groups=>the cost of a fixed household basket'
};
function sharpenSimulation(field,p,i){const text=simulationExperiments[field[0]]?.split(';')[i];if(!text)return p;const [change,outcome]=text.split('=>');p.question=`How does changing ${change} affect ${outcome}?`;p.artifact=`A browser experiment about ${p.title.toLowerCase()}. Let users change ${change}, then plot ${outcome}.`;p.method=`Make a small, clearly stated model. Compare two values or rules for ${change}; keep other inputs fixed. Record ${outcome} in both runs. Repeat random simulations with several starting seeds. Explain the assumptions; simulated results are not proof about real people or systems.`;p.evaluate=`Calculate one tiny example by hand and check your code matches it. Compare ${outcome} across the two settings. Show both the result and the assumptions that could change it.`;p.start=`Build one tiny case with at most 10 items, agents, or time steps. Run it twice with different settings for ${change}. Write down how ${outcome} changed.`;return p;}
function extendCatalog(library,sources){Object.assign(sources,extraSources);for(const field of expandedFields){library[field[0]]=field[4].split('|').map((topic,i)=>sharpenSimulation(field,makeCatalogProject(field,topic,i),i));}return Object.values(library).reduce((n,p)=>n+p.length,0);}
